INPUT_PATH: INPUT/teste/
OUTPUT_PATH: OUTPUT/teste/
TAX_DATABASE_PATH: '/media/bioinfo/6tb_hdd/04_Blast_Databases/taxdb'
DATABASE_PATH:  /media/bioinfo/6tb_hdd/04_Blast_Databases/silva/silva # nt or 16s
